# Generated by Django 5.2.5 on 2025-09-02 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentgroup"),
        ("courses", "0001_initial"),
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_enrollments",
                        to="courses.course",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_enrollments",
                        to="accounts.studentgroup",
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "course")},
            },
        ),
    ]
