# courses/tasks.py
import os
import subprocess
import tempfile
import shutil

from celery import shared_task
from django.core.files.base import ContentFile
from google import genai
from utils.drive_service import upload_video_private
from django.apps import apps
import time

@shared_task(bind=True, autoretry_for=(Exception,), retry_backoff=30, retry_kwargs={"max_retries": 3})
def convert_lesson_to_pdf(self, lesson_id):
    """
    Converts Lesson.content_file to PDF and saves it to pdf_version.
    """
    # Safe import inside the function to avoid circular error
    from .models import Lesson

    try:
        lesson = Lesson.objects.get(id=lesson_id)
    except Lesson.DoesNotExist:
        return "Lesson not found"

    if not lesson.content_file:
        lesson.processing_status = "skipped"
        return "No file to convert"

    # Mark as processing
    lesson.processing_status = "processing"
    lesson.save(update_fields=["processing_status"])

    file_name, ext = os.path.splitext(lesson.content_file.name)
    ext = ext.lower()

    allowed_extensions = [".ppt", ".pptx", ".doc", ".docx", ".xls", ".xlsx"]
    if ext not in allowed_extensions:
        lesson.processing_status = "skipped"
        lesson.save(update_fields=["processing_status"])
        return f"Unsupported file type: {ext}"

    # 1. Create temp input file
    with tempfile.NamedTemporaryFile(delete=False, suffix=ext) as temp_input:
        lesson.content_file.open("rb")
        temp_input.write(lesson.content_file.read())
        lesson.content_file.close()
        temp_input_path = temp_input.name

    # 2. Temp output directory
    temp_output_dir = tempfile.mkdtemp()

    try:
        # 3. Run LibreOffice
        libreoffice_path = r"C:\Program Files\LibreOffice\program\soffice.exe"

        command = [
            libreoffice_path,
            '--headless',
            '--convert-to', 'pdf',
            '--outdir', temp_output_dir,
            temp_input_path
        ]
        subprocess.run(
            command,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        # 4. Find generated PDF (more reliable)
        pdf_files = [
            f for f in os.listdir(temp_output_dir) if f.lower().endswith(".pdf")
        ]

        if not pdf_files:
            raise RuntimeError("PDF not generated by LibreOffice")

        pdf_path = os.path.join(temp_output_dir, pdf_files[0])

        # 5. Save PDF
        with open(pdf_path, "rb") as pdf_file:
            pdf_name = f"{os.path.basename(file_name)}.pdf"
            lesson.pdf_version.save(
                pdf_name,
                ContentFile(pdf_file.read()),
                save=False,
            )

        lesson.processing_status = "completed"
        lesson.save(update_fields=["pdf_version", "processing_status"])

        return f"Success: PDF generated for Lesson {lesson_id}"

    except subprocess.CalledProcessError as e:
        lesson.processing_status = "failed"
        lesson.save(update_fields=["processing_status"])
        return f"LibreOffice failed: {e.stderr.decode(errors='ignore')}"

    except Exception as e:
        lesson.processing_status = "failed"
        lesson.save(update_fields=["processing_status"])
        raise e

    finally:
        if os.path.exists(temp_input_path):
            os.remove(temp_input_path)
        if os.path.exists(temp_output_dir):
            shutil.rmtree(temp_output_dir)

@shared_task
def process_lesson_ai_summary(previous_result, lesson_id):
    from .models import Lesson # Avoid circular import
    print(previous_result)
    lesson = Lesson.objects.get(id=lesson_id)
    pdf_path = lesson.pdf_file.path
    
    # 1. Initialize Gemini
    client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
    
    # 2. Upload PDF to Gemini (or extract text manually)
    # For simplicity, we'll extract text or send the file directly
    with open(pdf_path, 'rb') as doc:
        response = client.models.generate_content(
            model="gemini-1.5-flash",
            contents=[
                "Summarize this lesson content in 5 key bullet points for a student knowledge base.",
                doc
            ]
        )
    
    # 3. Save the summary back to the Lesson model
    lesson.ai_summary = response.text
    lesson.save()


@shared_task
def upload_lesson_video_to_drive(lesson_id):
    Lesson = apps.get_model('courses', 'Lesson')
    try:
        lesson = Lesson.objects.get(id=lesson_id)
        
        # Check if file exists
        if not lesson.video_file_temp or not os.path.exists(lesson.video_file_temp.path):
            return "No file to upload"

        # Update status to Processing
        lesson.video_status = 'processing'
        lesson.save(update_fields=['video_status'])

        file_path = lesson.video_file_temp.path

        # -------------------------------------------------------------
        # STEP 1: AI Video Analysis (Must happen while local file exists)
        # -------------------------------------------------------------
        print(f"Starting Gemini AI Video Analysis for Lesson {lesson_id}...")
        try:
            client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
            
            # Upload to Gemini File API
            gemini_file = client.files.upload(file=file_path)
            
            # Wait for Gemini processing (videos take time to parse frames)
            while gemini_file.state.name == "PROCESSING":
                print("Waiting for Gemini to process video frames...")
                time.sleep(10)
                gemini_file = client.files.get(name=gemini_file.name)
                
            if gemini_file.state.name == "FAILED":
                print("Gemini video processing failed, skipping AI summary.")
                lesson.ai_summary = "AI processing failed for this video."
            else:
                # Ask Gemini to watch the video and write the summary
                response = client.models.generate_content(
                    model="gemini-2.0-flash",
                    contents=[
                        gemini_file,
                        "Analyze this educational video. Provide a detailed summary, "
                        "extract key conceptual definitions, list code implementations or diagrams shown, "
                        "and provide helpful student study notes."
                    ]
                )
                lesson.ai_summary = response.text
                
                # Cleanup from Gemini Cloud storage
                client.files.delete(name=gemini_file.name)
                print("✅ AI Analysis complete and saved to lesson.")
                
        except Exception as ai_err:
            print(f"⚠️ AI Processing error (Skipping but continuing upload): {ai_err}")
            lesson.ai_summary = f"AI Analysis failed: {ai_err}"

        # -------------------------------------------------------------
        # STEP 2: Your Original Google Drive Upload Logic
        # -------------------------------------------------------------
        print(f"Uploading video to Google Drive for Lesson {lesson_id}...")
        
        # Call your existing custom uploader function
        file_id = upload_video_private(file_path)

        drive_fake_url = f"https://drive.google.com/file/d/{file_id}/preview"

        # Update Lesson with both Drive URL and AI Data
        lesson.video_url = drive_fake_url
        lesson.video_status = 'completed'
        
        # Cleanup (Delete the temp file from disk and DB field)
        lesson.video_file_temp.storage.delete(lesson.video_file_temp.name)
        lesson.video_file_temp = None 
        
        # Save all updated metrics safely
        lesson.save(update_fields=['video_url', 'video_status', 'video_file_temp', 'ai_summary'])
        
        return f"Upload & AI Analysis Successful. Drive ID: {file_id}"

    except Exception as e:
        print(f"Video Task Failed: {e}")
        try:
            lesson = Lesson.objects.get(id=lesson_id)
            lesson.video_status = 'failed'
            lesson.save(update_fields=['video_status'])
        except:
            pass
        return f"Failed: {e}"