# courses/tasks.py
import os
import subprocess
import tempfile
import shutil

from celery import shared_task
from django.core.files.base import ContentFile
from django.apps import apps


@shared_task(bind=True, autoretry_for=(Exception,), retry_backoff=30, retry_kwargs={"max_retries": 3})
def convert_lesson_to_pdf(self, lesson_id):
    """
    Converts Lesson.content_file to PDF and saves it to pdf_version.
    """

    Lesson = apps.get_model('courses', 'Lesson')

    try:
        lesson = Lesson.objects.get(id=lesson_id)
    except Lesson.DoesNotExist:
        return "Lesson not found"

    if not lesson.content_file:
        return "No file to convert"

    # Mark as processing
    lesson.processing_status = "processing"
    lesson.save(update_fields=["processing_status"])

    file_name, ext = os.path.splitext(lesson.content_file.name)
    ext = ext.lower()

    allowed_extensions = [".ppt", ".pptx", ".doc", ".docx", ".xls", ".xlsx"]
    if ext not in allowed_extensions:
        lesson.processing_status = "skipped"
        lesson.save(update_fields=["processing_status"])
        return f"Unsupported file type: {ext}"

    # 1. Create temp input file
    with tempfile.NamedTemporaryFile(delete=False, suffix=ext) as temp_input:
        lesson.content_file.open("rb")
        temp_input.write(lesson.content_file.read())
        lesson.content_file.close()
        temp_input_path = temp_input.name

    # 2. Temp output directory
    temp_output_dir = tempfile.mkdtemp()

    try:
        # 3. Run LibreOffice
        libreoffice_path = r"C:\Program Files\LibreOffice\program\soffice.exe"

        command = [
            libreoffice_path,
            '--headless',
            '--convert-to', 'pdf',
            '--outdir', temp_output_dir,
            temp_input_path
        ]
        subprocess.run(
            command,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        # 4. Find generated PDF (more reliable)
        pdf_files = [
            f for f in os.listdir(temp_output_dir) if f.lower().endswith(".pdf")
        ]

        if not pdf_files:
            raise RuntimeError("PDF not generated by LibreOffice")

        pdf_path = os.path.join(temp_output_dir, pdf_files[0])

        # 5. Save PDF
        with open(pdf_path, "rb") as pdf_file:
            pdf_name = f"{os.path.basename(file_name)}.pdf"
            lesson.pdf_version.save(
                pdf_name,
                ContentFile(pdf_file.read()),
                save=False,
            )

        lesson.processing_status = "completed"
        lesson.save(update_fields=["pdf_version", "processing_status"])

        return f"Success: PDF generated for Lesson {lesson_id}"

    except subprocess.CalledProcessError as e:
        lesson.processing_status = "failed"
        lesson.save(update_fields=["processing_status"])
        return f"LibreOffice failed: {e.stderr.decode(errors='ignore')}"

    except Exception as e:
        lesson.processing_status = "failed"
        lesson.save(update_fields=["processing_status"])
        raise e

    finally:
        if os.path.exists(temp_input_path):
            os.remove(temp_input_path)
        if os.path.exists(temp_output_dir):
            shutil.rmtree(temp_output_dir)
